config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/not_yet', to: 'pages#not_yet', as: :not_yet
  resources :professors, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/professor.rb
class Professor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def not_yet
  end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  def index
    @professors = Professor.all
    @professor = Professor.new
  end

  def show
  end

  def edit
  end

  def create
    @professor = Professor.new(professor_params)

    if @professor.save
      redirect_to @professor, notice: 'Professor was successfully created.'
    else
      render :new
    end
  end

  def update
    if @professor.update(professor_params)
      redirect_to @professor, notice: 'Professor was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @professor.destroy
    redirect_to professors_url, notice: 'Professor was successfully destroyed.'
  end

  private
    def set_professor
      @professor = Professor.find(params[:id])
    end

    def professor_params
      params.require(:professor).permit(:name, :department, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
        when "notice" then "alert alert-info alert-dismissible fade show"
        when "success" then "alert alert-success alert-dismissible fade show"
        when "error" then "alert alert-danger alert-dismissible fade show"
    end
  end

  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/layouts/_flash_messages.html.haml
- flash.each do |key, value|
  %p{class: flash_class(key), role: "alert"}
    = value
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} &times;

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-md.navbar-dark.bg-primary
  = link_to 'Rails University', root_path, class: 'navbar-brand'
  %button.navbar-toggler{type: "button", "data-toggle": "collapse", "data-target": "#navbarNav", "aria-controls": "navbarNav", "aria-expanded": "false", "aria-label": "Toggle navigation"}
    %span.navbar-toggler-icon
  .collapse.navbar-collapse#navbarNav
    %ul.navbar-nav
      %li.navbar-item
        = link_to 'Professors', professors_path, class: "nav-link #{active_class(professors_path)}"

app/views/layouts/_model_errors.html.haml
- if model.invalid?
  .alert.alert-danger
    %ul
      - model.errors.full_messages.each do |message|
        %li=message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, user-scalable=no", :name => "viewport"}/
    %title Rails University
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/flash_messages'
    .container-fluid
      = yield

app/views/pages/home.html.haml
.jumbotron
  %h1.mt-4.mb-4 Rails University
  %p.lead Best university in all around the world, by all experts. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  %hr
  %p You can study here and be also best all around the world. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  = link_to 'Register as a professor', professors_path, class: 'btn btn-primary'
  = link_to 'Enroll as a student', not_yet_path, class: 'btn btn-success'

app/views/pages/not_yet.html.haml
.jumbotron
  %h1.mt-4.mb-4 Not yet
  %p.lead This page has not been created yet. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  %hr
  = link_to 'Back', :back, class: 'btn btn-primary'

app/views/professors/_form.html.haml
.card.mb-4.mt-4.text-white.bg-primary
  .card-header
    %h1.text-center=title
  .card-body
    = form_with(model: professor, local: true) do |form|
      = render 'layouts/model_errors', model: professor
      .form-group
        = form.text_field :name, placeholder: :name, class: "form-control"
      .form-group
        = form.text_field :department, placeholder: :department, class: "form-control"
      .form-group
        = form.email_field :email, placeholder: :email, class: "form-control"
      .form-group.text-center
        = form.submit "Register", class: "btn btn-success"
        = link_to "Cancel", root_path, class: "btn btn-danger"

app/views/professors/_professor.html.haml
= link_to professor, class: 'list-group-item list-group-item-action list-group-item-primary' do
  = professor.name

app/views/professors/_professor_details.html.haml
.card
  .card-header
    %h3 Professor details
  .card-body
    %p
      %b Name:
      = professor.name
    %p
      %b Department:
      = professor.department
    %p
      %b E-mail:
      = professor.email
  .card-footer
    = link_to 'Edit my profile', edit_professor_path(professor), class: 'btn btn-warning'
    = link_to 'Leave Rails University', professor, method: 'delete', class: 'btn btn-danger', data: { confirm: 'Are you sure you want to abandon your students? :(' }

app/views/professors/edit.html.haml
.row
  .col-12.col-md-6.offset-md-3
    = render 'form', title: 'Edit my profile', professor: @professor

app/views/professors/index.html.haml
%h1.text-center.mt-4.mb-4 Our excellent professors

.row
  .col-12.col-md-5.offset-md-1
    %h2 Professors list
    - if @professors.blank?
      .alert.alert-success We are waiting for some great professors to join!
    - else
      .list-group
        = render @professors
  .col-12.col-md-5
    %h2 Do you want to join us?
    = render 'form', title: 'Register as professor', professor: @professor

app/views/professors/show.html.haml
.row.mt-4.mb-4
  .col-12.col-md-4.offset-md-1
    = render 'professor_details', professor: @professor